[package]
name = "ls"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
chrono = { version = "0.4", features = ["clock"] }
humansize = "2.1"
owo-colors = "4.0"
atty = "0.2"
